"""
Self-Evolution: Plugin Automaker.
Rocky writes his own plugins, saves them to the plugins/ directory,
and hot-reloads his plugin manager to start using them immediately.

Safety: All generated plugins require user confirmation before being saved.
"""

import os
import re
import logging
import importlib
from brain.llm import generate_response

import ast

# 🛡️ SECURITY: Asterisk Import Whitelists and AST Enforcement
_ALLOWED_IMPORTS = ["os", "json", "datetime", "requests", "re", "math", "time"]
_DANGEROUS_PATTERNS = [
    r"subprocess", r"eval\(", r"exec\(", r"__import__", r"compile\(",
    r"shutil\.rmtree", r"os\.remove", r"os\.system", r"open\([^\)]+,\s*['\"]w"
]

_SAFE_OS_METHODS = {
    "listdir", "getcwd", "path", "stat", "environ", "getenv",
    "cpu_count", "urandom", "sep", "linesep", "pathsep"
}

class PluginSecurityVisitor(ast.NodeVisitor):
    def __init__(self):
        self.violation = None

    def visit_Import(self, node):
        for alias in node.names:
            if alias.name.split('.')[0] not in _ALLOWED_IMPORTS:
                self.violation = f"Blocked: Unauthorized import '{alias.name}'"
        self.generic_visit(node)

    def visit_ImportFrom(self, node):
        if node.module and node.module.split('.')[0] not in _ALLOWED_IMPORTS:
            self.violation = f"Blocked: Unauthorized import from '{node.module}'"
        self.generic_visit(node)

    def visit_Call(self, node):
        if isinstance(node.func, ast.Attribute):
            if isinstance(node.func.value, ast.Name) and node.func.value.id == "os":
                if node.func.attr not in _SAFE_OS_METHODS:
                    self.violation = f"Blocked: os.{node.func.attr} is not permitted in plugins."
        elif isinstance(node.func, ast.Name):
            if node.func.id in ("eval", "exec", "compile", "__import__"):
                self.violation = f"Blocked: {node.func.id}() is not permitted."
        self.generic_visit(node)


def _is_safe_plugin(code: str) -> str | None:
    """Scan plugin code using AST to enforce import allowlists and safe OS methods."""
    # 1. Regex checks
    for pattern in _DANGEROUS_PATTERNS:
        match = re.search(pattern, code, re.IGNORECASE)
        if match:
            return f"Blocked: dangerous pattern detected — `{match.group()}`"
            
    # 2. AST Sandbox checks
    try:
        tree = ast.parse(code)
        visitor = PluginSecurityVisitor()
        visitor.visit(tree)
        if visitor.violation:
            return visitor.violation
    except SyntaxError:
        return "Blocked: Plugin code has invalid syntax."
        
    return None

PLUGINS_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "plugins")

_PLUGIN_PROMPT = """You are a Python code generator. Write a minimal, functional Piper plugin file.

RULES:
1. The file MUST have a module-level list called KEYWORDS — these are the voice trigger phrases.
2. The file MUST have a function called execute(query: str) -> str that does the work.
3. Use only these exact permitted imports: import os, import json, import datetime, import requests, import re, import math, import time.
4. The function must return a human-readable string result.
5. Keep it under 40 lines.
6. Do NOT include any explanation — output ONLY the raw Python code. No markdown fences.

EXAMPLE:
KEYWORDS = ["water intake", "log water", "how much water"]

_log = []

def execute(query: str) -> str:
    if "log" in query.lower():
        _log.append(1)
        return f"Logged. Total glasses today: {len(_log)}."
    return f"You have logged {len(_log)} glasses of water today."

USER REQUEST: {request}
"""


def generate_plugin(user_request: str) -> dict:
    """
    Ask the LLM to generate a plugin.
    Returns {"filename": str, "code": str, "keywords": list} or {"error": str}.
    """
    prompt = _PLUGIN_PROMPT.format(request=user_request)
    raw = generate_response(prompt, history=[])

    # Strip JSON wrapper if LLM returns one
    code = raw.strip()
    if code.startswith("{"):
        import json
        try:
            parsed = json.loads(code)
            code = parsed.get("response", code)
        except Exception:
            pass

    # Strip markdown fences
    code = re.sub(r"^```\w*\n?", "", code)
    code = re.sub(r"\n?```$", "", code)
    code = code.strip()

    if "KEYWORDS" not in code or "def execute" not in code:
        return {"error": "Generated code is missing KEYWORDS or execute(). Try rephrasing."}

    # 🛡️ SECURITY: Scan code
    violation = _is_safe_plugin(code)
    if violation:
        logging.warning(f"[SELF-EVOLVE] Plugin rejected: {violation}")
        return {"error": f"Security violation in generated plugin: {violation}"}

    # Prepend auto-generated header
    code = f"# AUTO-GENERATED BY ROCKY\n{code}"

    # Extract keywords for preview
    kw_match = re.search(r"KEYWORDS\s*=\s*\[([^\]]+)\]", code)
    keywords = []
    if kw_match:
        keywords = [k.strip().strip("\"'") for k in kw_match.group(1).split(",")]

    # Generate a filename from the first keyword
    name = keywords[0] if keywords else "custom_plugin"
    filename = re.sub(r"[^a-z0-9]+", "_", name.lower()).strip("_") + ".py"

    return {"filename": filename, "code": code, "keywords": keywords}


def save_plugin(filename: str, code: str) -> str:
    """Save the generated plugin to disk and hot-reload the plugin manager."""
    filepath = os.path.join(PLUGINS_DIR, filename)
    try:
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(code)

        # Hot-reload the plugin manager
        from actions import plugins_manager
        importlib.reload(plugins_manager)

        logging.info(f"[SELF-EVOLVE] Plugin saved and loaded: {filename}")
        return f"Plugin '{filename}' saved and active. I can now respond to those commands."
    except Exception as e:
        logging.error(f"[SELF-EVOLVE] Save failed: {e}")
        return f"Failed to save plugin: {e}"
